# Script generated by Chat GPT

# Given the provided FXML content for lines and circles that represent a grid,
# we will center the grid in the Pane by adjusting the starting points of lines and center points of circles.

# Define the size of the grid and the Pane
pane_width = 1000
pane_height = 800
grid_size = 510  # Originally 16 cells, now 17 cells * 30px per cell

# Calculate the offset to center the grid in the Pane
offset_x = (pane_width - grid_size) / 2
offset_y = (pane_height - grid_size) / 2

# Generate the FXML content with the centered grid
fxml_content_centered = '''<?xml version="1.0" encoding="UTF-8"?>
<?import javafx.scene.layout.Pane?>
<?import javafx.scene.shape.Circle?>
<?import javafx.scene.shape.Line?>

<Pane prefHeight="800.0" prefWidth="1000.0" xmlns="http://javafx.com/javafx/8" xmlns:fx="http://javafx.com/fxml/1" fx:controller="fr.nathzaf.projects.morpionsolitaire.game.gui.JoinFiveController">
'''
# Add Vertical Lines
for i in range(0, 18):  # 17 cells + 1 for the last line, was 17 now 18
    start_x = i * 30 + offset_x
    start_y = offset_y
    end_y = grid_size + offset_y
    fxml_content_centered += f'  <Line startX="{start_x}" startY="{start_y}" endX="{start_x}" endY="{end_y}" stroke="BLACK"/>\n'

# Add Horizontal Lines
for i in range(0, 18):  # 17 cells + 1 for the last line, was 17 now 18
    start_x = offset_x
    end_x = grid_size + offset_x
    start_y = i * 30 + offset_y
    fxml_content_centered += f'  <Line startX="{start_x}" startY="{start_y}" endX="{end_x}" endY="{start_y}" stroke="BLACK"/>\n'

# Add Circles with unique IDs
for i in range(1, 17):  # 17 cells horizontally
    for j in range(1, 17):  # 17 cells vertically
        center_x = (i * 30) + offset_x
        center_y = ((17 - j) * 30) + offset_y  # We start from the bottom for y
        id = f'x{i-1}y{j-1}'  # ID based on grid position
        fxml_content_centered += f'  <Circle fx:id="{id}" opacity="0" centerX="{center_x}" centerY="{center_y}" radius="5" fill="BLACK" onMouseClicked="#selectPoint"/>\n'

# Close the Pane tag
fxml_content_centered += '</Pane>'

# Write the FXML content to a file
fxml_file_path_centered = '/Users/nathzaf/Dev/Py/morpion-solitaire/grid.fxml'
with open(fxml_file_path_centered, 'w') as fxml_file:
    fxml_file.write(fxml_content_centered)

fxml_file_path_centered
